spring:
  application:
    name: Fullapp
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: fullapp-scheduling-
      pool:
        size: 2
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: fullapp-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  security:
    user:
      roles: ADMIN
      name: admin
      password: $2a$12$cRKS9ZURbdJIaRsKDTDUmOrH4.B.2rokv8rrkrQXr2IR2Hkna484O
logging:
  level:
    tech:
      jhipster:
        fullapp: INFO
server:
  port: 8081
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    # Git Information
    git:
      mode: full
      enabled: true
    env:
      enabled: true
application:
  logging:
    logstash:
      tcp:
        shutdown_grace_period: PT1M
        enabled: false
        ring-buffer-size: 8192
        host: localhost
        port: 5000
  security:
    jwt-base64-secret: NmE2NDhmMmQ5OWQzYzk4NmE4NjNlMmQzNmU3ZTU4ZDY2MmUxOWEwZGI4YTk4NDY0MTk4MmQyMWZlNDNlM2FjYg==
    remember-me-token-validity: P365D
    token-validity: P1D
    content-security-policy: 'default-src ''self''; frame-src ''self'' data:; script-src
      ''self'' ''unsafe-inline'' ''unsafe-eval'' https://storage.googleapis.com; style-src
      ''self'' ''unsafe-inline'' https://fonts.googleapis.com; img-src ''self'' data:;
      font-src ''self'' data: https://fonts.gstatic.com;'
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
  enable-native-support: true
