spring:
  application:
    name: Fullapp
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: fullapp-scheduling-
      pool:
        size: 2
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: fullapp-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
logging:
  level:
    tech:
      jhipster:
        fullapp: INFO
server:
  port: 8081
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
application:
  logging:
    logstash:
      tcp:
        shutdown_grace_period: PT1M
        enabled: false
        ring-buffer-size: 8192
        host: localhost
        port: 5000
